name: Build Project

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
      
jobs:
  build-project:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      fail-fast: true
    steps:
      - uses: actions/checkout@v2
      - name: Build the app
        run: ./gradlew build

